# Generated by Django 4.2.6 on 2023-10-28 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order_creator", "0003_car_order_delete_orderquantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logedinuser",
            old_name="user",
            new_name="client",
        ),
    ]
