# Generated by Django 4.2.6 on 2023-10-28 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order_creator", "0004_rename_user_logedinuser_client"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LogedInUser",
            new_name="LoggedInUser",
        ),
    ]
